# Generated by Django 4.1.5 on 2023-01-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clientmodel_owner_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmodel',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='fact_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='jurist_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
