# Generated by Django 4.1.5 on 2023-02-06 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0004_alter_clientmodel_owner_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='owner_manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
