# Generated by Django 4.1.5 on 2023-02-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_clientmodel_owner_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='trend_licetin',
            field=models.BooleanField(default=False, verbose_name='лицетин'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='trend_manez',
            field=models.BooleanField(default=False, verbose_name='майонез'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='trend_no_raf',
            field=models.BooleanField(default=False, verbose_name='не рафинированное масло'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='trend_raf',
            field=models.BooleanField(default=False, verbose_name='рафинированное масло'),
        ),
    ]
