# Generated by Django 4.1.5 on 2023-03-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_clientmodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
