# Generated by Django 4.1.5 on 2023-01-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_groupproductmodel_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproductmodel',
            name='group_title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
