# Generated by Django 4.1.5 on 2023-01-29 18:44

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_groupproductmodel_group_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('declination', models.FileField(blank=True, null=True, upload_to=product.models.content_file_name)),
                ('protocol', models.FileField(blank=True, null=True, upload_to=product.models.content_file_name)),
                ('specification', models.FileField(blank=True, null=True, upload_to=product.models.content_file_name)),
                ('quality_certificate', models.FileField(blank=True, null=True, upload_to=product.models.content_file_name)),
                ('product_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.groupproductmodel')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
