# Generated by Django 4.1.5 on 2023-01-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='declination',
            new_name='declaration',
        ),
    ]
