# Generated by Django 4.1.5 on 2023-01-31 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productmodel_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='article',
            field=models.CharField(max_length=20, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_group', to='product.groupproductmodel', verbose_name='Группа продукта'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(max_length=250, verbose_name='Наименование проукта'),
        ),
    ]
