# Generated by Django 4.1.5 on 2023-01-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productmodel_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='article',
            field=models.CharField(max_length=20, verbose_name='Артикул'),
        ),
    ]
