# Generated by Django 4.1.5 on 2023-01-31 12:42

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productmodel_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='declaration',
            field=models.FileField(blank=True, null=True, upload_to=product.models.content_file_name, verbose_name='Декларация'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='protocol',
            field=models.FileField(blank=True, null=True, upload_to=product.models.content_file_name, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quality_certificate',
            field=models.FileField(blank=True, null=True, upload_to=product.models.content_file_name, verbose_name='Сертификат качества'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='specification',
            field=models.FileField(blank=True, null=True, upload_to=product.models.content_file_name, verbose_name='Спецификация продукта'),
        ),
    ]
