# Generated by Django 4.1.5 on 2023-02-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productmodel_declaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='цена'),
        ),
    ]
