# Generated by Django 4.1.5 on 2023-02-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackagingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing', models.CharField(default='ящик из гофрированного картона', max_length=255, verbose_name='упаковка')),
                ('netto', models.PositiveIntegerField(verbose_name='нетто масса товара в одной единице упаковки')),
                ('brutto', models.PositiveIntegerField(verbose_name='брутто масса одной коробки с товаром')),
                ('quantity_box', models.PositiveIntegerField(verbose_name='количество коробок на поддоне')),
                ('pallet_weight_netto', models.PositiveIntegerField(blank=True, null=True, verbose_name='масса поддона нетто')),
                ('pallet_weight_brutto', models.PositiveIntegerField(blank=True, null=True, verbose_name='масса поддона брутто')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.productmodel')),
            ],
        ),
    ]
