# Generated by Django 4.1.5 on 2023-02-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productpackagingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackagingmodel',
            name='brutto',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='брутто масса одной коробки с товаром'),
        ),
        migrations.AlterField(
            model_name='productpackagingmodel',
            name='netto',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='нетто масса товара в одной единице упаковки'),
        ),
        migrations.AlterField(
            model_name='productpackagingmodel',
            name='pallet_weight_brutto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='масса поддона брутто'),
        ),
        migrations.AlterField(
            model_name='productpackagingmodel',
            name='pallet_weight_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='масса поддона нетто'),
        ),
    ]
