# Generated by Django 4.1.5 on 2023-02-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productmodel_packing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackagingmodel',
            name='packing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='упаковка'),
        ),
    ]
