# Generated by Django 4.1.5 on 2023-02-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productpackagingmodel_packing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpackagingmodel',
            name='packing',
        ),
        migrations.AddField(
            model_name='productpackagingmodel',
            name='packing_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='упаковка'),
        ),
    ]
