# Generated by Django 4.1.5 on 2023-02-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_productpackagingmodel_packing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackagingmodel',
            name='brutto',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='брутто масса (коробка/ведро)'),
        ),
        migrations.AlterField(
            model_name='productpackagingmodel',
            name='netto',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='нетто масса товара (коробка/ведро)'),
        ),
        migrations.AlterField(
            model_name='productpackagingmodel',
            name='quantity_box',
            field=models.PositiveIntegerField(verbose_name='количество (коробка/ведро) на поддоне'),
        ),
    ]
