# Generated by Django 4.1.5 on 2023-02-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_productpackagingmodel_brutto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_type',
            field=models.CharField(choices=[('T', 'продукт тарированный'), ('W', 'продукт весовой'), ('S', 'продукт сыпучий'), ('N', 'продукт не указан')], default='N', max_length=20),
        ),
    ]
