# Generated by Django 4.1.5 on 2023-02-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_productmodel_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackagingmodel',
            name='quantity_element_in',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='количество единиц в упакове'),
        ),
    ]
