# Generated by Django 4.1.5 on 2023-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_productmodel_weigth_netto_alter_productmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='цена'),
        ),
    ]
