# Generated by Django 4.1.5 on 2023-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_productmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackagingmodel',
            name='quantity_element_in',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='количество единиц в упакове'),
        ),
    ]
