# Generated by Django 4.1.5 on 2023-02-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_productmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='weigth_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='вес нетто'),
        ),
    ]
