# Generated by Django 4.1.5 on 2023-02-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_productpackagingmodel_packing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackagingmodel',
            name='packing_name',
            field=models.CharField(choices=[('AJ', 'ящик из гофрированного картона'), ('K', 'канистра'), ('P', 'пластиковое ведро с крышкой'), ('T', 'сыпучий товар')], default='AJ', max_length=40, verbose_name='упаковка'),
        ),
    ]
