# Generated by Django 4.1.5 on 2023-02-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_productpackagingmodel_packing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spe_packing', to='product.productpackagingmodel', verbose_name='спецификация упаковки'),
        ),
    ]
