# Generated by Django 4.1.5 on 2023-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_tradeproductbasketmodel_quantity_pr1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademodel',
            name='stage',
        ),
        migrations.AddField(
            model_name='trademodel',
            name='stage_name',
            field=models.CharField(choices=[(1, 'согласование клиента'), (2, 'коммерческое предложение'), (3, 'подписание договора'), (4, 'оплата'), (5, 'исполнение договора'), (6, 'завершение сделки')], default=1, max_length=30),
        ),
        migrations.DeleteModel(
            name='TradeStage',
        ),
    ]
