# Generated by Django 4.1.5 on 2023-02-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_remove_trademodel_stage_trademodel_stage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='stage_name',
            field=models.CharField(choices=[('1', 'согласование клиента'), ('2', 'коммерческое предложение'), ('3', 'подписание договора'), ('4', 'оплата'), ('5', 'исполнение договора'), ('6', 'завершение сделки')], default=1, max_length=30),
        ),
    ]
