# Generated by Django 4.1.5 on 2023-02-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_alter_trademodel_create_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trademodel',
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
    ]
