# Generated by Django 4.1.5 on 2023-02-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_alter_trademodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
