# Generated by Django 4.1.5 on 2023-02-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_productpackagingmodel_quantity_element_in'),
        ('trade', '0011_alter_tradeitemmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitemmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_product', to='product.productmodel'),
        ),
        migrations.AlterField(
            model_name='tradeitemmodel',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_trade', to='trade.trademodel'),
        ),
    ]
