# Generated by Django 4.1.5 on 2023-02-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_alter_tradeitemmodel_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='full_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='общий вес'),
        ),
    ]
