# Generated by Django 4.1.5 on 2023-02-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_trademodel_full_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeitemmodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='полная стоимость'),
        ),
        migrations.AddField(
            model_name='tradeitemmodel',
            name='total_weight_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='общий вес'),
        ),
    ]
