# Generated by Django 4.1.5 on 2023-02-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_remove_tradeitemmodel_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitemmodel',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
