# Generated by Django 4.1.5 on 2023-02-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_alter_tradeitemmodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='compare',
            field=models.BooleanField(default=False),
        ),
    ]
