# Generated by Django 4.1.5 on 2023-02-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0020_alter_tradeitemmodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='compare',
            field=models.BooleanField(default=False, verbose_name='согласование цены и количества'),
        ),
    ]
