# Generated by Django 4.1.5 on 2023-02-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0021_alter_trademodel_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='logistic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='логистика'),
        ),
    ]
