# Generated by Django 4.1.5 on 2023-03-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_productmodel_packing'),
        ('trade', '0025_remove_tradeagentmodel_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeAgentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('date_delivery', models.DateField(verbose_name='дата поставки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена поставщика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel', verbose_name='продукт')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.trademodel', verbose_name='сделка')),
            ],
        ),
    ]
