# Generated by Django 4.1.5 on 2023-03-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0026_tradeagentitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeagentitem',
            name='trade',
        ),
        migrations.CreateModel(
            name='TradeAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.trademodel', verbose_name='сделка')),
            ],
        ),
        migrations.AddField(
            model_name='tradeagentitem',
            name='trade_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.tradeagent', verbose_name='заявка'),
        ),
    ]
