# Generated by Django 4.1.5 on 2023-03-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0027_remove_tradeagentitem_trade_tradeagent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeagent',
            name='full_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='общий вес'),
        ),
        migrations.AlterField(
            model_name='tradeagent',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='сумма'),
        ),
    ]
