# Generated by Django 4.1.5 on 2023-03-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0028_tradeagent_full_weight_alter_tradeagent_full_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='application_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='trade.tradeitemmodel', verbose_name='заявка поставщикам'),
        ),
    ]
