# Generated by Django 4.1.5 on 2023-03-06 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0029_trademodel_application_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='application_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='trade.tradeagent', verbose_name='заявка поставщикам'),
        ),
    ]
