# Generated by Django 4.1.5 on 2023-03-06 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_productmodel_packing'),
        ('trade', '0030_alter_trademodel_application_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeagentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.productmodel', verbose_name='продукт'),
        ),
    ]
